name: 'QMLDiff hasher'
description: 'Hashes QMD files, copies structure and pushes to a public repository'
inputs:
  source_root:
    description: 'Root folder with source files'
    required: false
    default: ''
  hashtab_root:
    description: 'Root folder containing hashtab files'
    required: true
  dest_repo_name:
    description: 'The name of the destination, public repo (f.ex. user/repository)'
    required: true
  repo_access_token:
    description: 'The token to use when pushing to the public repo'
    required: true
  commit_message:
    description: 'Custom commit message for the destination repo (defaults to Updated/Created {name} for fw {fw})'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/pepikvaio/remarkable_qmldiff-hasher-action:main'

